[build]
  functions = "api"

[functions]
  # هذا السطر يخبر Netlify بتحزيم ملفات Python داخل مجلد api
  included_files = ["api/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
